baseURL = 'https://meruman.github.io/'
languageCode = 'en-us'
title = 'Martin MeRu'
theme = 'PortfolioTheme'
[markup.highlight]
  codeFences = false

[markup.tableOfContents]
  endLevel = 3
  ordered = false
  startLevel = 3